name: ai_chat_assistant
description: A Flutter package for AI-powered chat functionality with OpenAI integration. Simple integration with a single FloatingChatButton widget.
version: 2.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  logger: ^2.6.0
  fin_api_functions:
    git:
      url: https://github.com/fineratech/FinPackages.git
      path: fin_api_functions
  web_socket_channel: ^3.0.3
  record: ^6.1.2
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  flutter_webrtc: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
