name: ai_chat_assistant
description: A Flutter package for AI-powered chat functionality with OpenAI integration. Simple integration with a single FloatingChatButton widget.
version: 2.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  logger: ^2.6.0
  fin_api_functions:
    git:
      url: https://github.com/fineratech/FinPackages.git
      path: fin_api_functions
  web_socket_channel: ^2.4.0
  record: ^5.0.0
  audioplayers: ^5.2.0
  permission_handler: ^11.0.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
