name: bank_details
description: "A new FinPackage for adding bank details"
version: 0.0.1
homepage: "https://example.com"
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  csc_picker_plus: ^0.0.3
  file_picker: ^8.0.5
  image_cropper: ^8.0.2
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  control_style: ^0.1.0
  flutter_credit_card: ^4.0.1
  logger: ^2.2.0
  fin_commons:
    git:
      url: https://github.com/fineratech/FinPackages.git
      path: fin_commons
  fin_api_functions:
    git:
      url: https://github.com/fineratech/FinPackages.git
      path: fin_api_functions
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
